name: Lint, Test, Codecov

on: [push, pull_request]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.17' ]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      -
        name: Test
        run: V=1 make ci

  codecov:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Test
        run: V=1 make test
      -
        name: Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
