name: Test, Codecov

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.21' ]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      -
        name: Test
        run: V=1 make ci

  codecov:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.18
      -
        name: Test
        run: V=1 make test
      -
        name: Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.out # optional
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}